[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.39.0",
    "groq>=0.31.1",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.43",
    "streamlit>=1.50.0",
]
